name: 'Jophiel '
favicon: null
layout_spectrum: 0.74535
typography_spectrum: 0.54865
title: Jophiel Silvestrone
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b88357'
    - '#d0c4ae'
    - '#fffffd'
    - '#403f45'
  brandStrength: 0.0625
  lightness: 0.875
  saturation: 0.2944931525271386
  rhythmicContrast: 0.19243218121118844
purpose: []
