name: 'Jophiel '
favicon: null
layout_spectrum: 0.49692
typography_spectrum: 0.54865
title: Jophiel Silvestrone
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe3e4'
    - '#374047'
    - '#9f9784'
    - '#b90317'
    - '#f18624'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.2944931525271386
  rhythmicContrast: 0.19243218121118844
purpose: []
