name: 'Jophiel '
favicon: null
layout_spectrum: 0.4995
typography_spectrum: 0.54865
title: "Hello, I'm Jophiel - CEO/Owner of SkyPoint Studios"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffee9'
    - '#e3c59f'
    - '#76716e'
    - '#5a4540'
    - '#b79d84'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
