name: 'Jophiel '
favicon: null
layout_spectrum: 0.4995
typography_spectrum: 0.54865
title: Who is Jophiel Silvestrone?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151c26'
    - '#52609e'
    - '#8e9dfc'
    - '#8b4200'
    - '#dca25c'
  brandStrength: 0.0625
  lightness: 0.875
  saturation: 0.2944931525271386
  rhythmicContrast: 0.19243218121118844
purpose: []
