name: 'Jophiel '
favicon: null
layout_spectrum: 0.97747
typography_spectrum: 0.54865
title: Jophiel Silvestrone
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e959b'
    - '#000600'
    - '#ffffff'
    - '#9b630e'
    - '#9b0e1f'
  brandStrength: 0.0625
  lightness: 0.875
  saturation: 0.2944931525271386
  rhythmicContrast: 0.19243218121118844
purpose: []
